package com.aallam.openai.api.chat;

import com.aallam.openai.api.BetaOpenAI
import com.aallam.openai.api.core.FinishReason
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A completion generated by OpenAI.
 *
 * [documentation](https://platform.openai.com/docs/api-reference/chat/create)
 */
@Serializable
data class ChatChoice(
    /**
     * Chat choice index.
     */
    @SerialName("index") val index: Int,
    /**
     * The generated chat message.
     */
    @SerialName("message") val message: ChatMessage,

    /**
     * The reason why OpenAI stopped generating.
     */
    @SerialName("finish_reason") val finishReason: FinishReason? = null,
)
